// Clinical Features for Input Form
export const CLINICAL_FEATURES = [
  {
    id: 'age',
    label: 'Age',
    type: 'number',
    placeholder: 'Enter age (years)',
    unit: 'years',
    min: 18,
    max: 120,
    category: 'demographics',
  },
  {
    id: 'sex',
    label: 'Sex',
    type: 'select',
    options: ['Male', 'Female'],
    category: 'demographics',
  },
  {
    id: 'bmi',
    label: 'BMI',
    type: 'number',
    placeholder: 'Body Mass Index',
    unit: 'kg/m²',
    min: 10,
    max: 60,
    category: 'vitals',
  },
  {
    id: 'systolic_bp',
    label: 'Systolic BP',
    type: 'number',
    placeholder: 'Systolic Blood Pressure',
    unit: 'mmHg',
    min: 60,
    max: 250,
    category: 'vitals',
  },
  {
    id: 'diastolic_bp',
    label: 'Diastolic BP',
    type: 'number',
    placeholder: 'Diastolic Blood Pressure',
    unit: 'mmHg',
    min: 40,
    max: 150,
    category: 'vitals',
  },
  {
    id: 'resting_pulse',
    label: 'Resting Pulse',
    type: 'number',
    placeholder: 'Resting Heart Rate',
    unit: 'bpm',
    min: 30,
    max: 200,
    category: 'vitals',
  },
  {
    id: 'cognitive_score',
    label: 'Cognitive Test Score',
    type: 'number',
    placeholder: 'MoCA/MMSE Score',
    unit: 'points',
    min: 0,
    max: 30,
    category: 'clinical',
  },
  {
    id: 'years_education',
    label: 'Years of Education',
    type: 'number',
    placeholder: 'Total years',
    unit: 'years',
    min: 0,
    max: 30,
    category: 'demographics',
  },
  {
    id: 'smoking_history',
    label: 'Smoking History',
    type: 'select',
    options: ['Never', 'Former', 'Current'],
    category: 'lifestyle',
  },
  {
    id: 'family_history_pd',
    label: 'Family History of PD',
    type: 'select',
    options: ['Yes', 'No', 'Unknown'],
    category: 'clinical',
  },
];

// Top Biomarkers identified (from research)
export const BIOMARKERS = [
  {
    id: 1,
    name: 'Alpha-Synuclein',
    symbol: 'SNCA',
    importance: 0.95,
    description: 'Primary component of Lewy bodies, hallmark of PD pathology',
    category: 'Protein Aggregation',
    direction: 'elevated',
  },
  {
    id: 2,
    name: 'Neurofilament Light Chain',
    symbol: 'NfL',
    importance: 0.89,
    description: 'Marker of neuronal damage and axonal degeneration',
    category: 'Neurodegeneration',
    direction: 'elevated',
  },
  {
    id: 3,
    name: 'DJ-1 Protein',
    symbol: 'PARK7',
    importance: 0.84,
    description: 'Antioxidant protein linked to oxidative stress in PD',
    category: 'Oxidative Stress',
    direction: 'decreased',
  },
  {
    id: 4,
    name: 'Glucocerebrosidase',
    symbol: 'GBA',
    importance: 0.81,
    description: 'Lysosomal enzyme; mutations increase PD risk',
    category: 'Lysosomal Function',
    direction: 'decreased',
  },
  {
    id: 5,
    name: 'BDNF',
    symbol: 'BDNF',
    importance: 0.78,
    description: 'Brain-derived neurotrophic factor supporting neuron survival',
    category: 'Neuroprotection',
    direction: 'decreased',
  },
  {
    id: 6,
    name: 'Urate',
    symbol: 'UA',
    importance: 0.72,
    description: 'Antioxidant; lower levels associated with PD risk',
    category: 'Antioxidant',
    direction: 'decreased',
  },
  {
    id: 7,
    name: 'Apolipoprotein A1',
    symbol: 'APOA1',
    importance: 0.68,
    description: 'Lipid metabolism protein with neuroprotective properties',
    category: 'Lipid Metabolism',
    direction: 'decreased',
  },
  {
    id: 8,
    name: 'Inflammatory Cytokines',
    symbol: 'IL-6/TNF-α',
    importance: 0.65,
    description: 'Markers of neuroinflammation in PD',
    category: 'Inflammation',
    direction: 'elevated',
  },
];

// Dataset Statistics
export const DATASET_STATS = {
  participants: 18645,
  cohorts: 23,
  bioSamples: 31083,
  proteomicAssays: 35056,
  proteinMeasurements: '~250 million',
  clinicalFeatures: 40,
  platforms: ['SomaScan 7K', 'SomaScan 5K', 'SomaScan 1.3K'],
  diseases: ['Parkinson\'s Disease', 'Alzheimer\'s Disease', 'ALS', 'FTD'],
};

// Model Performance Metrics
export const MODEL_METRICS = {
  accuracy: 0.94,
  sensitivity: 0.92,
  specificity: 0.96,
  auc: 0.97,
  precision: 0.93,
  f1Score: 0.925,
};

export default {
  CLINICAL_FEATURES,
  BIOMARKERS,
  DATASET_STATS,
  MODEL_METRICS,
};

